project_id = "edxkisyskfazjmqpburj"

[functions.openai-proxy]
verify_jwt = true

[functions.assistant-manager]
verify_jwt = true

[functions.thread-manager]
verify_jwt = true

[functions.assistant-run]
verify_jwt = true

[functions.studio-chat]
verify_jwt = true
