project_id = "edxkisyskfazjmqpburj"

[functions.openai-proxy]
verify_jwt = true

[functions.conversation-manager]
verify_jwt = true

[functions.thread-manager]
verify_jwt = true

[functions.conversation-run]
verify_jwt = true

[functions.studio-chat]
verify_jwt = true

[functions.confluence-manager]
verify_jwt = true